name: Build
on:
    pull_request:
        types: [opened, synchronize]
    workflow_dispatch:
permissions:
    contents: write
    pull-requests: write
jobs:
    build:
        if: github.actor == 'dependabot[bot]' || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-slim
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # main
              with:
                  egress-policy: audit
            - name: 准备 Socket Firewall
              uses: socketdev/action@ba6de6cc0565af1f42295590380973573297e31f # main
              with:
                  mode: firewall
            - name: 签出
              uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231 # main
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: 准备 pnpm
              uses: step-security/action-setup@0ad50dc56a23060fa78b14cfcf0677c4e14b42bc # main
              with:
                  version: latest
                  cache: true
            - name: 准备 node.js
              uses: actions/setup-node@670825a89dc0abd596e7a3abd0f5e3f6e5faf37c # main
              with:
                  node-version: 24
                  cache: pnpm
                  check-latest: true
            - name: 安装 pnpm 依赖
              run: sfw pnpm install
            - name: 构建
              run: |
                  pnpm run build
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add -A
                  git diff --staged --quiet || git commit -m "pnpm"
                  git push
