name: Build
on:
    pull_request:
        types: [opened, synchronize]
    workflow_dispatch:
permissions:
    contents: read
jobs:
    build:
        if: github.actor == 'dependabot[bot]' || github.event_name == 'workflow_dispatch'
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # main
              with:
                  egress-policy: audit
            - name: 准备 Socket Firewall
              uses: socketdev/action@ba6de6cc0565af1f42295590380973573297e31f # main
              with:
                  mode: firewall
            - name: 签出
              uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231 # main
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: 准备 node.js
              uses: actions/setup-node@0355742c943ddb13ca8a6b700f824231caa91e75 # main
              with:
                  node-version: 24
                  check-latest: true
            - name: 准备 pnpm
              uses: step-security/action-setup@0ad50dc56a23060fa78b14cfcf0677c4e14b42bc # main
              with:
                  version: latest
                  cache: true
            - name: 安装 pnpm 依赖
              run: sfw pnpm install
            - name: 构建
              run: |
                  node --run build
            - name: 提交
              uses: step-security/ghcommit-action@da34a5bfeb80f309e05b4f5f1be06ea83659ba44 #main
              with:
                  commit_message: "pnpm"
                  repo: ${{ github.repository }}
                  branch: ${{ github.head_ref || github.ref_name }}
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
